# Default initial positions for baxter's ros2_control fake system

initial_positions:
  l_gripper_l_finger_joint: 0
  left_e0: 0
  left_e1: 0
  left_s0: 0
  left_s1: 0
  left_w0: 0
  left_w1: 0
  left_w2: 0
  r_gripper_l_finger_joint: 0
  right_e0: 0
  right_e1: 0
  right_s0: 0
  right_s1: 0
  right_w0: 0
  right_w1: 0
  right_w2: 0